"""
MediLedger Nigeria — ZK Vault Client
Fills the two stubs in inference/engine.py:
  get_vault_proof(nhia_id)   → GET  zk-vault-service:3012/api/v1/zk/proof/:nhia_id
  verify_zk_proof(proof)     → POST zk-vault-service:3012/api/v1/zk/verify
Internal access only — x-internal-key header required.
"""
from __future__ import annotations

import logging
import os

import httpx

logger = logging.getLogger(__name__)

ZK_SERVICE_URL = os.environ.get("ZK_VAULT_SERVICE_URL", "http://zk-vault-service:3012")
INTERNAL_KEY   = os.environ.get("INTERNAL_API_KEY", "")
TIMEOUT        = 10.0  # seconds — proof retrieval from Redis is fast; allow margin


def _headers() -> dict[str, str]:
    return {"x-internal-key": INTERNAL_KEY, "Content-Type": "application/json"}


async def get_vault_proof(patient_nhia_id: str) -> dict:
    """
    Retrieve the latest sealed vault proof for a patient.
    Proof is generated by zk-vault-service on every record upload and cached in Redis (24h TTL).
    Raises httpx.HTTPStatusError if proof not found (vault not yet sealed).
    """
    url = f"{ZK_SERVICE_URL}/api/v1/zk/proof/{patient_nhia_id}"
    async with httpx.AsyncClient() as client:
        resp = await client.get(url, headers=_headers(), timeout=TIMEOUT)
        resp.raise_for_status()
        proof_data = resp.json()
        logger.debug(f"Vault proof retrieved for {patient_nhia_id}: {proof_data.get('proofHash', '')[:16]}…")
        return proof_data  # { proof, publicSignals, proofHash, vaultCommitment, recordRoot, generatedAt }


async def verify_zk_proof(vault_proof: dict) -> bool:
    """
    Verify a Groth16 vault integrity proof.
    Returns True if valid, False if tampered/invalid.
    Raises on network error — caller should treat network error as verification failure.
    """
    url = f"{ZK_SERVICE_URL}/api/v1/zk/verify"
    payload = {
        "proof":         vault_proof["proof"],
        "publicSignals": vault_proof["publicSignals"],
    }
    async with httpx.AsyncClient() as client:
        resp = await client.post(url, json=payload, headers=_headers(), timeout=TIMEOUT)
        resp.raise_for_status()
        result = resp.json()
        valid = result.get("valid", False)
        logger.debug(f"Vault proof verification result: {valid}")
        return valid


async def get_condition_proof(patient_nhia_id: str, condition_code: int) -> dict | None:
    """
    Retrieve a pre-generated condition proof from the emergency Redis cache.
    Returns None if not yet pre-generated (emergency service should call prove-condition first).
    Used by emergency-service for sub-10ms condition checks (Redis GET + verify).
    """
    url = f"{ZK_SERVICE_URL}/api/v1/zk/condition-proof/{patient_nhia_id}/{condition_code}"
    async with httpx.AsyncClient() as client:
        resp = await client.get(url, headers=_headers(), timeout=TIMEOUT)
        if resp.status_code == 404:
            return None
        resp.raise_for_status()
        return resp.json()
