// Auto-generated by: supabase gen types typescript --local > lib/database.types.ts
// Run after schema migrations to keep types in sync.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: {
      user_roles: {
        Row: {
          id: string;
          user_id: string;
          role: 'patient' | 'provider' | 'hmo' | 'nhia' | 'researcher';
          nhia_id: string | null;
          facility_id: string | null;
          created_at: string;
        };
        Insert: Omit<Database['public']['Tables']['user_roles']['Row'], 'id' | 'created_at'>;
        Update: Partial<Database['public']['Tables']['user_roles']['Insert']>;
      };
      patients: {
        Row: {
          id: string;
          user_id: string;
          nhia_id: string;
          hedera_account_id: string | null;
          full_name: string;
          date_of_birth: string;
          gender: 'M' | 'F' | 'Other' | null;
          phone_number: string;
          blood_type: 'A+' | 'A-' | 'B+' | 'B-' | 'AB+' | 'AB-' | 'O+' | 'O-' | null;
          emergency_tag_active: boolean;
          vault_public_key: string;
          zk_proof_hash: string;
          heal_balance: number;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['patients']['Row'], 'id' | 'created_at' | 'updated_at'>;
        Update: Partial<Database['public']['Tables']['patients']['Insert']>;
      };
      health_records: {
        Row: {
          id: string;
          patient_id: string;
          record_type: 'lab' | 'imaging' | 'prescription' | 'consultation' | 'vaccination' | 'surgical';
          facility_id: string;
          fhir_resource_type: string;
          storage_path: string;
          record_hash: string;
          hcs_sequence_number: number | null;
          hcs_topic_id: string | null;
          is_emergency_access: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['health_records']['Row'], 'id' | 'created_at' | 'updated_at'>;
        Update: Partial<Database['public']['Tables']['health_records']['Insert']>;
      };
      consent_agreements: {
        Row: {
          id: string;
          patient_id: string;
          requester_user_id: string;
          requester_type: 'provider' | 'hmo' | 'researcher' | 'emergency' | null;
          data_scope: Json;
          purpose: string;
          monthly_payment_heal: number;
          status: 'active' | 'expired' | 'revoked' | 'pending';
          valid_from: string;
          valid_until: string;
          hcs_message_id: string | null;
          revoked_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['consent_agreements']['Row'], 'id' | 'created_at' | 'updated_at'>;
        Update: Partial<Database['public']['Tables']['consent_agreements']['Insert']>;
      };
      insurance_claims: {
        Row: {
          id: string;
          patient_id: string;
          provider_user_id: string;
          hmo_user_id: string | null;
          nhia_program_id: string | null;
          service_date: string;
          icd10_codes: string[];
          total_amount_ngn: number;
          approved_amount_ngn: number | null;
          status: 'draft' | 'submitted' | 'provider_signed' | 'patient_signed' | 'hmo_review' | 'approved' | 'rejected' | 'paid' | 'disputed';
          patient_sig_hash: string | null;
          provider_sig_hash: string | null;
          hmo_sig_hash: string | null;
          smart_contract_tx_id: string | null;
          sla_deadline: string | null;
          sla_breached: boolean;
          rejection_reason: string | null;
          processed_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['insurance_claims']['Row'], 'id' | 'created_at' | 'updated_at'>;
        Update: Partial<Database['public']['Tables']['insurance_claims']['Insert']>;
      };
      token_transactions: {
        Row: {
          id: string;
          from_patient_id: string | null;
          to_patient_id: string | null;
          consent_id: string | null;
          amount_heal: number;
          tx_type: 'consent_payment' | 'onboarding_bonus' | 'claim_reward' | 'withdrawal' | null;
          hedera_tx_id: string | null;
          status: 'pending' | 'confirmed' | 'failed';
          created_at: string;
        };
        Insert: Omit<Database['public']['Tables']['token_transactions']['Row'], 'id' | 'created_at'>;
        Update: Partial<Database['public']['Tables']['token_transactions']['Insert']>;
      };
    };
  };
};
